### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by pgilad**

### CODE REVIEW

**Comment by lukekarrys** [comment]
+1

**Comment by pgilad** [comment]
@lukekarrys Thanks for all the reviews... I pushed version 3.6.0 but can't publish on npm (no rights :cry: )

Can you publish version 3.6.0 ?

**Comment by lukekarrys** [comment]
@pgilad Published as `3.6.0` to npm and added you as an owner for next time :smile:

**Comment by pgilad** [comment]
:clap:

**Pull request merged**
