### PR TITLE
Add ability to set visibility property with toggle binding (GH-26)

### PR DESCRIPTION
**Pull request by remixz**
Fixes GH-26.

Not too much to say about this, I think. Enjoy!

### CODE REVIEW

**Comment by lukekarrys** [comment]
Pending https://github.com/AmpersandJS/ampersand-dom/pull/10 I'm a +1 on this as well.

**Comment by lukekarrys** [comment]
Travis passed now that https://github.com/AmpersandJS/ampersand-dom/pull/10 has been merged/published.

**Comment by wraithgar** [comment]
+1 Looks good. Should we be worried about the failing test above or is that a remnant of getting travis working?

**Comment by wraithgar** [comment]
Looks like when I click that failing test it's a passing test?

**Comment by lukekarrys** [comment]
Yeah, I reran travis and one of the checks updated in GitHub but not the other, but they both saying passing on travis now :shrug:

**Comment by lukekarrys** [comment]
Published as `v3.5.0`

**Pull request merged**
